# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/workflows/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Build with Gradle
        id: build-with-gradle
        run: ./gradlew build

      - name: Upload tests report
        id: upload-tests-report
        if: failure() && steps.build-with-gradle.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: tests-report-files
          path: build/reports/tests
          if-no-files-found: error

      - name: Upload Jar
        id: upload-jar
        if: success() && steps.build-with-gradle.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: jar-files
          path: build/libs/*-SNAPSHOT.jar
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-files

      - name: List all downloaded files
        run: ls
